### ISSUE TITLE
curses.error: addwstr() returned ERR [BUG]

### ISSUE THREAD

**Issue by shayandavoodii** [vfarid/cf-ip-scanner#14]
سلام، بعد از پیدا شدن چندتا آیپی قبل از fulfill شدن تنظیماتی که ست کرده بودم این ارور رو برگردوند:
```
Traceback (most recent call last):
  File "<PATH>\cf-ip-scanner-py-1.4\start.py", line 2710, in <module>
    main()
  File "<PATH>\cf-ip-scanner-py-1.4\start.py", line 209, in main
    selectd_ip_list, total_test = curses.wrapper(startTest, ip_list=ip_list, config=config)
  File "<PATH>\AppData\Local\Programs\Python\Python310\lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "<PATH>\cf-ip-scanner-py-1.4\start.py", line 295, in startTest
    stdscr.addstr(x + 1, y, str)
_curses.error: addwstr() returned ERR
```

**Comment by vfarid** [comment]
مرتبط با این کتابخانه نیست ولی باید پکیج windows-courses رو با pip نصب کنید.

**Comment by shayandavoodii** [comment]
نصب کرده بودم.
